package wilds

import (
	"encoding/json"
	"os"
	"testing"
)

func jsonMarshal(v any) ([]byte, error) { return json.Marshal(v) }

func same(t *testing.T, label string, a, b any) {
	t.Helper()
	aa, _ := json.Marshal(a)
	bb, _ := json.Marshal(b)
	var x, y any
	_ = json.Unmarshal(aa, &x)
	_ = json.Unmarshal(bb, &y)
	ax, _ := json.Marshal(x)
	by, _ := json.Marshal(y)
	if string(ax) != string(by) {
		t.Fatalf("%s\ngot %s\nwant %s", label, ax, by)
	}
}

// TestTypeScriptParity replays content/vectors/wilds.json, generated by
// npm run vectors:wilds from the TypeScript generator. A stale file fails
// tests/wilds-vectors.test.ts first.
func TestTypeScriptParity(t *testing.T) {
	b, err := os.ReadFile("../../../content/vectors/wilds.json")
	if err != nil {
		t.Fatal(err)
	}
	var v struct {
		ChunkSeeds []struct {
			WorldSeed        string `json:"worldSeed"`
			RegionID         string `json:"regionId"`
			GeneratorVersion int    `json:"generatorVersion"`
			Season           string `json:"season"`
			CX               int    `json:"cx"`
			CY               int    `json:"cy"`
			Result           uint32 `json:"result"`
		} `json:"chunkSeeds"`
		LootSeeds []struct {
			WorldSeed        string `json:"worldSeed"`
			RegionID         string `json:"regionId"`
			GeneratorVersion int    `json:"generatorVersion"`
			Season           string `json:"season"`
			EntityID         string `json:"entityId"`
			Cycle            int    `json:"cycle"`
			Result           uint32 `json:"result"`
		} `json:"lootSeeds"`
		Entities []struct {
			Epoch  Epoch `json:"epoch"`
			Chunks []struct {
				CX       int      `json:"cx"`
				CY       int      `json:"cy"`
				Entities []Entity `json:"entities"`
			} `json:"chunks"`
		} `json:"entities"`
		Loot []struct {
			Epoch    Epoch    `json:"epoch"`
			EntityID string   `json:"entityId"`
			Cycle    int      `json:"cycle"`
			Drop     LootDrop `json:"drop"`
		} `json:"loot"`
	}
	if err = json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	for _, c := range v.ChunkSeeds {
		got := ChunkSeed(Epoch{WorldSeed: c.WorldSeed, RegionID: c.RegionID, GeneratorVersion: c.GeneratorVersion, Season: c.Season}, c.CX, c.CY)
		if got != c.Result {
			t.Fatalf("chunk seed %s/%s v%d %s (%d,%d) = %d want %d", c.WorldSeed, c.RegionID, c.GeneratorVersion, c.Season, c.CX, c.CY, got, c.Result)
		}
	}
	for _, c := range v.LootSeeds {
		got := LootSeed(Epoch{WorldSeed: c.WorldSeed, RegionID: c.RegionID, GeneratorVersion: c.GeneratorVersion, Season: c.Season}, c.EntityID, c.Cycle)
		if got != c.Result {
			t.Fatalf("loot seed %s %s cycle %d = %d want %d", c.EntityID, c.Season, c.Cycle, got, c.Result)
		}
	}
	chunks := 0
	for _, epoch := range v.Entities {
		for _, c := range epoch.Chunks {
			got, err := ChunkEntities(epoch.Epoch, c.CX, c.CY)
			if err != nil {
				t.Fatal(err)
			}
			same(t, "entities", got, c.Entities)
			chunks++
		}
	}
	for _, c := range v.Loot {
		got, err := RollLoot(c.Epoch, c.EntityID, c.Cycle)
		if err != nil {
			t.Fatal(err)
		}
		same(t, "loot", got, c.Drop)
	}
	t.Logf("replayed %d chunk seeds, %d loot seeds, %d entity chunks and %d loot rolls", len(v.ChunkSeeds), len(v.LootSeeds), chunks, len(v.Loot))
}
