/**
 * Writes content/vectors/homestead.json: homestead land generated by the
 * TypeScript generator (src/lib/homestead-land.ts) for a spread of worlds
 * and gates, which the Go port (server/internal/land) must reproduce tile
 * for tile, plus lantern post prices.
 *
 * Run: npm run vectors:homestead
 */
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { generateLand, landRows, landSeed, postCost } from '../src/lib/homestead-land.ts';

const WORLDS = ['guest', 'world-1', '灰烬之路', 'a1b2c3d4e5f6'];
const GATES = [0, 1, 2, 7, 31, 999];

export function homesteadVectors() {
  const lands = [];
  for (const worldId of WORLDS) {
    for (const gate of GATES) {
      const seed = landSeed(worldId, gate);
      lands.push({ worldId, gate, seed, rows: landRows(generateLand(seed)) });
    }
  }
  const posts = Array.from({ length: 7 }, (_, n) => ({ n, cost: postCost(n) }));
  return { lands, posts };
}

export function serializeHomesteadVectors(): string {
  return `${JSON.stringify(homesteadVectors())}\n`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  writeFileSync(new URL('../content/vectors/homestead.json', import.meta.url), serializeHomesteadVectors());
}
