/**
 * Papers generator: docs/lore/texts/*.md (the owner's found texts) →
 * src/content/papers-text.ts (titles, descriptions, collections, provenance
 * and bodies as data). Run `npm run papers` after editing a text; the
 * generated file is committed, and tests/papers.test.ts fails if it drifts
 * from the markdown, so the docs stay the single source of the words.
 *
 * Where each paper is found (and how it looks when read) is hand-authored
 * in src/content/papers.ts — that is design, not text.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export interface PaperMeta {
  label: string;
  value: string;
}

export interface PaperTextRecord {
  id: string;
  title: string;
  description: string;
  collection: string;
  meta: PaperMeta[];
  body: string;
}

const META_LABELS = [
  'Author',
  'Date',
  'Material',
  'Location Found',
  'Issued By',
  'Dictated to',
  'Annotations by',
  'Subject',
  'Magistrate',
];

/** README sections → [collection, [{ file, title, description }]] in order. */
export function parseReadme(readme: string): { collection: string; file: string; title: string; description: string }[] {
  const out: { collection: string; file: string; title: string; description: string }[] = [];
  let collection = '';
  for (const raw of readme.split('\n')) {
    const line = raw.trim();
    const heading = /^##\s+(.+)$/.exec(line);
    if (heading) {
      collection = heading[1].trim();
      continue;
    }
    // | [Title](file.md) | Description |
    const row = /^\|\s*\[(.+?)\]\(([^)]+\.md)\)\s*\|\s*(.+?)\s*\|$/.exec(line);
    if (row && collection) out.push({ collection, title: row[1].trim(), file: row[2].trim(), description: row[3].trim() });
  }
  return out;
}

/** Strip the H1, lift the provenance lines, drop the "*From …*" footer. */
export function parseText(md: string): { meta: PaperMeta[]; body: string } {
  const lines = md.replace(/\r\n/g, '\n').split('\n');
  let i = 0;
  while (i < lines.length && lines[i].trim() === '') i++;
  if (i < lines.length && /^#\s/.test(lines[i])) i++;
  const meta: PaperMeta[] = [];
  // Provenance block: consecutive **Label:** lines (blank lines between allowed).
  for (;;) {
    while (i < lines.length && lines[i].trim() === '') i++;
    const m = /^\*\*([^*]+?):\*\*\s*(.*)$/.exec(lines[i]?.trim() ?? '');
    if (!m || !META_LABELS.includes(m[1].trim())) break;
    meta.push({ label: m[1].trim(), value: m[2].trim() });
    i++;
  }
  let rest = lines.slice(i);
  // Footer: the collection attribution, always the last non-blank line.
  while (rest.length && rest[rest.length - 1].trim() === '') rest.pop();
  if (rest.length && /^\*From\s+["“]/.test(rest[rest.length - 1].trim())) rest.pop();
  rest = rest.map((l) => l.replace(/\s+$/, ''));
  while (rest.length && rest[rest.length - 1].trim() === '') rest.pop();
  while (rest.length && rest[0].trim() === '') rest.shift();
  // Collapse runs of blank lines to one.
  const body: string[] = [];
  for (const l of rest) if (!(l === '' && body[body.length - 1] === '')) body.push(l);
  return { meta, body: body.join('\n') };
}

/** Curly quotes for display strings (the bodies keep the writer's own). */
function typeset(s: string): string {
  return s.replace(/"([^"]+)"/g, '“$1”').replace(/'/g, '’');
}

export function buildRecords(readme: string, files: Record<string, string>): PaperTextRecord[] {
  return parseReadme(readme).map((entry) => {
    const md = files[entry.file];
    if (md === undefined) throw new Error(`[papers] README lists ${entry.file}, which does not exist`);
    const { meta, body } = parseText(md);
    return {
      id: entry.file.replace(/\.md$/, ''),
      title: typeset(entry.title),
      description: typeset(entry.description),
      collection: entry.collection,
      meta,
      body,
    };
  });
}

export function renderModule(records: PaperTextRecord[]): string {
  const collections = [...new Set(records.map((r) => r.collection))];
  return [
    '// Generated by scripts/papers.ts from docs/lore/texts — do not edit by hand.',
    '// Edit the markdown, then run `npm run papers`.',
    '',
    'export interface PaperMeta {',
    '  label: string;',
    '  value: string;',
    '}',
    '',
    'export interface PaperTextRecord {',
    '  id: string;',
    '  title: string;',
    '  /** One line, from docs/lore/texts/README.md. */',
    '  description: string;',
    "  /** The README section it sits under. */",
    '  collection: string;',
    '  /** Provenance lines (Author, Date, Material…). */',
    '  meta: PaperMeta[];',
    '  /** Markdown-ish body: parse with src/lib/papers/markup.ts. */',
    '  body: string;',
    '}',
    '',
    `export const PAPER_COLLECTIONS: readonly string[] = ${JSON.stringify(collections, null, 2)};`,
    '',
    `export const PAPER_TEXTS: readonly PaperTextRecord[] = ${JSON.stringify(records, null, 2)};`,
    '',
  ].join('\n');
}

export function readTexts(dir: URL): { readme: string; files: Record<string, string> } {
  const files: Record<string, string> = {};
  for (const name of readdirSync(dir)) {
    if (name.endsWith('.md') && name !== 'README.md') files[name] = readFileSync(new URL(name, dir), 'utf8');
  }
  return { readme: readFileSync(new URL('README.md', dir), 'utf8'), files };
}

export const TEXTS_DIR = new URL('../docs/lore/texts/', import.meta.url);
export const OUT_FILE = new URL('../src/content/papers-text.ts', import.meta.url);

export function generate(): string {
  const { readme, files } = readTexts(TEXTS_DIR);
  const records = buildRecords(readme, files);
  const listed = new Set(records.map((r) => `${r.id}.md`));
  const orphans = Object.keys(files).filter((f) => !listed.has(f));
  if (orphans.length) throw new Error(`[papers] texts missing from README: ${orphans.join(', ')}`);
  return renderModule(records);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(OUT_FILE, generate());
  console.log('Wrote src/content/papers-text.ts');
}
